name: 'Build application'

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Implementation goes here

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Implementation goes here
